"""Add reportes table

Revision ID: 004
Revises: 003
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('resumen_ejecutivo', sa.Text(), nullable=True),
    sa.Column('emociones_detectadas', sqlite.JSON, nullable=True),
    sa.Column('alertas_generadas', sqlite.JSON, nullable=True),
    sa.Column('recomendaciones', sqlite.JSON, nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('visible_estudiante', sa.Boolean(), nullable=False),
    sa.Column('metadatos', sqlite.JSON, nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_chat.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_creado_en'), 'reportes', ['creado_en'], unique=False)
    op.create_index(op.f('ix_reportes_estado'), 'reportes', ['estado'], unique=False)
    op.create_index(op.f('ix_reportes_estudiante'), 'reportes', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_reportes_sesion'), 'reportes', ['sesion_id'], unique=False)
    op.create_index(op.f('ix_reportes_tutor'), 'reportes', ['tutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportes_tutor'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_sesion'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_estudiante'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_estado'), table_name='reportes')
    op.drop_index(op.f('ix_reportes_creado_en'), table_name='reportes')
    op.drop_table('reportes')
    # ### end Alembic commands ### 